dist: trusty
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: pypy2.7-5.8.0
    env: TOXENV=pypy
install:
- pip install tox
script:
- tox
before_install:
- pip install codecov
after_success:
- tox -e coverage-report
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: spotify_alf
  password:
    secure: secure: "WibqSG8sMVmJ7tiXW+TjqbSZy3XbgAAznqsIuWNO9pfvfhSecScQV1sFqDn2HorBvd3davunJJDHbYCJs5jS+qtaOxTaOcN82qCIq6PKtgT7iXIpatvYejljDA1ftUprmUpRVQIP0w1f2m1P+xY8IgSqepX6gJ80yOyxNmhbSi4zyMkW6xxRGHOj7LJN7m1vJviD2Td6+EBqTS1y3BtJ1eFnBBm1qcqA66jthaFu3Oxs3VYJZtK9ZKLiX3MxZ8dwo/OuO5GM+BcEssiWOF75cQ8CS5c5+rDtxGK+Nwq3Jyj2/nlpCFqisMccnHZS+0+goEqTIpxUEb0TLm3tRL/yxaVAsNv6IVFrhLV3kQQhnGNRazA2lFYtSa1IG24zBtDWlHzi424hl4YDYkGbmxx2No18nGHafNKGnRx37WdSrReyXKQ7b1e9MoEdrqtyhaS9jG6ZndraqQZ8VZ3ruh4VQiHTGC3FabegXvJkoczPHx+TaopXwu/fuOVAw8CxAH+X0n7DA1kJKxEyf6M/o3AzRLgDKRnfUl4oCHsLKtiGeAwTQjWrfFJiS2pSwxB2a20S9L+b9xvF8HRFrGrKN8+vVnFBV5IwSaB3h9D87Ug+9ORA2aRloE4p/Kt3lEp97T3yVm/zDBmuuw1YmMkArvZdKQFU7jIulLAimTt7AFQaBag="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
